csv_path: /path/to/h5_index.csv
checkpoint_dir: /path/to/checkpoints
log_dir: /path/to/logs
backbone_name: r3d_18
h5_image_key: window_broad
target_hw: [224, 224]
target_d: auto_train_max
volume_batch_size: 2
use_dataset_zscore: true
training:
  lr_backbone: 0.00001
  lr_head: 0.0001
  early_stop_patience: 30
